version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - restored_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
      - run:
        name: test
        command: npm test
